export const TOOLS = [
  'road',
  'cobble',
  'bulldoze',
  'pier',
  'market',
  'house',
  'shop',
  'warehouse',
  'park',
];

export const DEFS = {
  road: {
    label: 'Road',
    cost: 50,
    upkeep: 0.08,
    pop: 0,
    jobs: 0,
    pollution: 0,
    category: 'infra',
    height: 0,
    footprint: 1,
    facade: null,
    roof: null,
    glass: false,
    windows: false,
  },
  cobble: {
    label: 'Cobble',
    cost: 80,
    upkeep: 0.1,
    pop: 0,
    jobs: 0,
    pollution: 0,
    category: 'infra',
    height: 0,
    footprint: 1,
    facade: null,
    roof: null,
    glass: false,
    windows: false,
  },
  bulldoze: {
    label: 'Bulldoze',
    cost: 0,
    upkeep: 0,
    pop: 0,
    jobs: 0,
    pollution: 0,
    category: 'infra',
    height: 0,
    footprint: 1,
    facade: null,
    roof: null,
    glass: false,
    windows: false,
  },
  park: {
    label: 'Park',
    cost: 300,
    upkeep: 0.4,
    pop: 0,
    jobs: 1,
    pollution: 0,
    happiness: 8,
    radius: 5,
    category: 'civic',
    height: 0,
    footprint: 1,
    facade: null,
    roof: null,
    glass: false,
    windows: false,
  },
  house: {
    label: 'Rowhouse',
    cost: 400,
    upkeep: 0.35,
    pop: 4,
    jobs: 0,
    pollution: 0,
    category: 'home',
    height: 6.15,
    footprint: 0.98,
    facade: 'rowhouse.jpg',
    roof: 'roof_shingle.jpg',
    glass: false,
    windows: true,
    upgrade: 'apartment',
    upgradeCost: 1450,
  },
  apartment: {
    label: 'Apartment',
    cost: 1800,
    upkeep: 1.6,
    pop: 24,
    jobs: 2,
    pollution: 0,
    category: 'home',
    height: 20,
    footprint: 0.84,
    facade: 'apartment.jpg',
    roof: 'roof_gravel.jpg',
    glass: false,
    windows: true,
    upgrade: 'tower',
    upgradeCost: 6400,
  },
  tower: {
    label: 'Tower',
    cost: 8000,
    upkeep: 6.5,
    pop: 80,
    jobs: 6,
    pollution: 0,
    category: 'home',
    height: 30,
    footprint: 0.78,
    facade: 'skyscraper.jpg',
    roof: 'roof_gravel.jpg',
    glass: true,
    windows: true,
  },
  market: {
    label: 'Market',
    cost: 850,
    upkeep: 0.85,
    pop: 0,
    jobs: 8,
    pollution: 0,
    commerce: true,
    waterfront: true,
    radius: 6,
    category: 'work',
    height: 4.6,
    footprint: 0.82,
    facade: 'storefront.jpg',
    roof: 'roof_shingle.jpg',
    glass: false,
    windows: true,
  },
  shop: {
    label: 'Shop',
    cost: 1200,
    upkeep: 1.2,
    pop: 0,
    jobs: 12,
    pollution: 0,
    commerce: true,
    radius: 7,
    category: 'work',
    height: 5.6,
    footprint: 0.86,
    facade: 'storefront.jpg',
    roof: 'roof_gravel.jpg',
    glass: false,
    windows: true,
  },
  office: {
    label: 'Office',
    cost: 3500,
    upkeep: 3.2,
    pop: 0,
    jobs: 40,
    pollution: 0,
    category: 'work',
    height: 28,
    footprint: 0.8,
    facade: 'office.jpg',
    roof: 'roof_gravel.jpg',
    glass: true,
    windows: true,
  },
  warehouse: {
    label: 'Warehouse',
    cost: 1100,
    upkeep: 1.15,
    pop: 0,
    jobs: 10,
    pollution: 0.35,
    radius: 6,
    category: 'work',
    height: 8.4,
    footprint: 0.9,
    facade: 'warehouse.jpg',
    roof: 'roof_gravel.jpg',
    glass: false,
    windows: true,
  },
  factory: {
    label: 'Factory',
    cost: 5000,
    upkeep: 4.5,
    pop: 0,
    jobs: 36,
    pollution: 0.8,
    radius: 8,
    category: 'work',
    height: 11,
    footprint: 0.9,
    facade: 'factory.jpg',
    roof: 'roof_gravel.jpg',
    glass: false,
    windows: true,
  },
  hospital: {
    label: 'Hospital',
    cost: 6000,
    upkeep: 7.0,
    pop: 0,
    jobs: 18,
    pollution: 0,
    service: 'health',
    beds: 120,
    radius: 10,
    category: 'civic',
    height: 16.5,
    footprint: 0.88,
    facade: 'hospital.jpg',
    roof: 'roof_gravel.jpg',
    glass: false,
    windows: true,
  },
  clinic: {
    label: 'Clinic',
    cost: 2200,
    upkeep: 2.4,
    pop: 0,
    jobs: 8,
    pollution: 0,
    service: 'health',
    beds: 40,
    radius: 7,
    category: 'civic',
    height: 7.4,
    footprint: 0.82,
    facade: 'hospital.jpg',
    roof: 'roof_shingle.jpg',
    glass: false,
    windows: true,
  },
  fire: {
    label: 'Firehouse',
    cost: 2800,
    upkeep: 3.1,
    pop: 0,
    jobs: 10,
    pollution: 0,
    service: 'fire',
    radius: 9,
    category: 'civic',
    height: 8.6,
    footprint: 0.9,
    facade: 'warehouse.jpg',
    roof: 'roof_shingle.jpg',
    glass: false,
    windows: true,
  },
  school: {
    label: 'School',
    cost: 4500,
    upkeep: 5.5,
    pop: 0,
    jobs: 12,
    pollution: 0,
    service: 'edu',
    seats: 90,
    radius: 8,
    category: 'civic',
    height: 9.2,
    footprint: 0.86,
    facade: 'school.jpg',
    roof: 'roof_shingle.jpg',
    glass: false,
    windows: true,
  },
  civic: {
    label: 'Civic',
    cost: 7000,
    upkeep: 8.0,
    pop: 0,
    jobs: 14,
    pollution: 0,
    service: 'civic',
    radius: 12,
    cityBonus: 1,
    category: 'civic',
    height: 13,
    footprint: 0.88,
    facade: 'civic.jpg',
    roof: 'roof_gravel.jpg',
    glass: false,
    windows: true,
  },
  power: {
    label: 'Plant',
    cost: 3200,
    upkeep: 4.2,
    pop: 0,
    jobs: 8,
    pollution: 0.7,
    capacity: 120,
    radius: 8,
    category: 'civic',
    height: 6.8,
    footprint: 0.9,
    facade: 'warehouse.jpg',
    roof: 'steel.jpg',
    glass: false,
    windows: false,
  },
  cistern: {
    label: 'Water tower',
    cost: 1600,
    upkeep: 1.8,
    pop: 0,
    jobs: 3,
    pollution: 0,
    capacity: 96,
    radius: 8,
    category: 'civic',
    height: 14.2,
    footprint: 0.52,
    facade: 'steel.jpg',
    roof: 'steel.jpg',
    glass: false,
    windows: false,
  },
  sewer: {
    label: 'Works',
    cost: 2600,
    upkeep: 3.4,
    pop: 0,
    jobs: 6,
    pollution: 0.22,
    capacity: 108,
    radius: 8,
    category: 'civic',
    height: 6.6,
    footprint: 0.88,
    facade: 'warehouse.jpg',
    roof: 'roof_gravel.jpg',
    glass: false,
    windows: false,
  },
  cable: {
    label: 'Cable',
    cost: 40,
    upkeep: 0.04,
    pop: 0,
    jobs: 0,
    pollution: 0,
    category: 'infra',
    height: 0,
    footprint: 1,
    facade: null,
    roof: null,
    glass: false,
    windows: false,
  },
  pier: {
    label: 'Pier',
    cost: 480,
    upkeep: 0.55,
    pop: 0,
    jobs: 4,
    pollution: 0,
    waterfront: true,
    category: 'infra',
    height: 0.4,
    footprint: 0.92,
    facade: null,
    roof: 'wood_dock.jpg',
    glass: false,
    windows: false,
  },
};

export const FALLBACK_COLORS = {
  'grass.jpg': 0x4d6b3d,
  'dirt.jpg': 0x6a5344,
  'sand.jpg': 0xc4ad7a,
  'water.jpg': 0x1a4e58,
  'asphalt.jpg': 0x2c2d30,
  'concrete.jpg': 0x8a8680,
  'cobble.jpg': 0x6d6860,
  'roof_gravel.jpg': 0x5c5a56,
  'roof_shingle.jpg': 0x3d332e,
  'wood_dock.jpg': 0x6b4e34,
  'rowhouse.jpg': 0x8b4a3a,
  'rowhouse_b.jpg': 0x8b4a3a,
  'rowhouse_c.jpg': 0x8b4a3a,
  'rowhouse_d.jpg': 0x8b4a3a,
  'rowhouse_e.jpg': 0xd8d0c4,
  'apartment.jpg': 0x9a7a62,
  'glass_res.jpg': 0x6a8a96,
  'storefront.jpg': 0x7a5a48,
  'office.jpg': 0x7c8890,
  'skyscraper.jpg': 0x5d7380,
  'warehouse.jpg': 0x7a7468,
  'factory.jpg': 0x5c5852,
  'hospital.jpg': 0xc9c2b4,
  'school.jpg': 0x9a6a4a,
  'civic.jpg': 0xa89a84,
  'night_windows.jpg': 0x1a1408,
  'oak.png': 0x3d5c32,
  'oak.jpg': 0x3d5c32,
  'pine.png': 0x2d4a30,
  'pine.jpg': 0x2d4a30,
  'maple.jpg': 0x4a6a30,
  'oak_top.jpg': 0x3d5c32,
  'pine_top.jpg': 0x2d4a30,
  'maple_top.jpg': 0x4a6a30,
  'leaves.jpg': 0x3f5c32,
  'needles.jpg': 0x2d4a30,
  'shrub.jpg': 0x314a2a,
  'sky.jpg': 0xb7c4d2,
  'hero.jpg': 0x2a241c,
  'plywood.jpg': 0xc4a56a,
  'scaffold.jpg': 0x8a9094,
  'tarp.jpg': 0x2a6cb0,
  'silt_fence.jpg': 0xc45a28,
  'steel.jpg': 0x4a4e52,
  'lumber.jpg': 0xc8a56a,
};

const BASE = import.meta.env.BASE_URL || '/';
function asset(rel) {
  return `${BASE}${String(rel).replace(/^\//, '')}`;
}

export const ASSET_PATHS = {
  'grass.jpg': asset('assets/textures/grass.jpg'),
  'dirt.jpg': asset('assets/textures/dirt.jpg'),
  'sand.jpg': asset('assets/textures/sand.jpg'),
  'water.jpg': asset('assets/textures/water.jpg'),
  'asphalt.jpg': asset('assets/textures/asphalt.jpg'),
  'concrete.jpg': asset('assets/textures/concrete.jpg'),
  'cobble.jpg': asset('assets/textures/cobble.jpg'),
  'roof_gravel.jpg': asset('assets/textures/roof_gravel.jpg'),
  'roof_shingle.jpg': asset('assets/textures/roof_shingle.jpg'),
  'wood_dock.jpg': asset('assets/textures/wood_dock.jpg'),
  'rowhouse.jpg': asset('assets/facades/rowhouse.jpg'),
  'rowhouse_b.jpg': asset('assets/facades/rowhouse_b.jpg'),
  'rowhouse_c.jpg': asset('assets/facades/rowhouse_c.jpg'),
  'rowhouse_d.jpg': asset('assets/facades/rowhouse_d.jpg'),
  'rowhouse_e.jpg': asset('assets/facades/rowhouse_e.jpg'),
  'apartment.jpg': asset('assets/facades/apartment.jpg'),
  'glass_res.jpg': asset('assets/facades/glass_res.jpg'),
  'storefront.jpg': asset('assets/facades/storefront.jpg'),
  'office.jpg': asset('assets/facades/office.jpg'),
  'skyscraper.jpg': asset('assets/facades/skyscraper.jpg'),
  'warehouse.jpg': asset('assets/facades/warehouse.jpg'),
  'factory.jpg': asset('assets/facades/factory.jpg'),
  'hospital.jpg': asset('assets/facades/hospital.jpg'),
  'school.jpg': asset('assets/facades/school.jpg'),
  'civic.jpg': asset('assets/facades/civic.jpg'),
  'night_windows.jpg': asset('assets/facades/night_windows.jpg'),
  'oak.png': asset('assets/props/oak.jpg'),
  'pine.png': asset('assets/props/pine.jpg'),
  'oak.jpg': asset('assets/props/oak.jpg'),
  'pine.jpg': asset('assets/props/pine.jpg'),
  'maple.jpg': asset('assets/props/maple.jpg'),
  'oak_top.jpg': asset('assets/props/oak_top.jpg'),
  'pine_top.jpg': asset('assets/props/pine_top.jpg'),
  'maple_top.jpg': asset('assets/props/maple_top.jpg'),
  'leaves.jpg': asset('assets/props/leaves.jpg'),
  'needles.jpg': asset('assets/props/needles.jpg'),
  'shrub.jpg': asset('assets/props/shrub.jpg'),
  'sky.jpg': asset('assets/env/sky.jpg'),
  'hero.jpg': asset('assets/env/hero.jpg'),
  'plywood.jpg': asset('assets/construct/plywood.jpg'),
  'scaffold.jpg': asset('assets/construct/scaffold.jpg'),
  'tarp.jpg': asset('assets/construct/tarp.jpg'),
  'silt_fence.jpg': asset('assets/construct/silt_fence.jpg'),
  'steel.jpg': asset('assets/construct/steel.jpg'),
  'lumber.jpg': asset('assets/construct/lumber.jpg'),
};

export function refundFor(type) {
  const def = DEFS[type];
  if (!def) return 0;
  return Math.floor(def.cost * 0.5);
}

export function isResidential(type) {
  return type === 'house' || type === 'apartment' || type === 'tower';
}

export function isWorkplace(type) {
  return (
    type === 'shop' ||
    type === 'market' ||
    type === 'office' ||
    type === 'warehouse' ||
    type === 'factory' ||
    type === 'hospital' ||
    type === 'clinic' ||
    type === 'school' ||
    type === 'civic' ||
    type === 'fire' ||
    type === 'power' ||
    type === 'cistern' ||
    type === 'sewer' ||
    type === 'pier' ||
    type === 'park'
  );
}
